### ISSUE TITLE
No More Meecast Widget on lock-screen 

### ISSUE THREAD

**Issue by nerfiaux** [CODeRUS/sailfishos-lockscreen-player-patch#2]
Hi Andrey,

I had the widget from weather forecast app meecast working,
and the I installed your patch.
I don't have the meecast widget anymore.
meecast daemon got updated v0.2-1 but still not displayed.
Could you please check if it comes from this patch ?
If not i will check with meecast dev.

Thanks Great Work !

**Comment by CODeRUS** [comment]
Not relevant to patch
